"""empty message

Revision ID: 72ca8fac9613
Revises: aff464f3fc37
Create Date: 2016-05-28 21:44:24.865381

"""

# revision identifiers, used by Alembic.
revision = '72ca8fac9613'
down_revision = 'aff464f3fc37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gridlayouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('scripts', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gridlayouts')
    ### end Alembic commands ###
