"""empty message

Revision ID: aff464f3fc37
Revises: aaeac1c10b6b
Create Date: 2016-05-28 19:48:36.103524

"""

# revision identifiers, used by Alembic.
revision = 'aff464f3fc37'
down_revision = 'aaeac1c10b6b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('color', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'color')
    ### end Alembic commands ###
